import { Policies } from './columns';

export const data: Policies[] = [
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
  {
    policyNumber: 'SLICO-1701698460658',
    customerName: 'Hero Paul Anie',
    coverType: 'Third Party',
    schedule: 'PRIVATE INDIVIDUAL',
    make: 'AUO 098	Toyota corolla',
    company: 'Sierra Leone Insurance Company',
    inception: '04-Dec-2023',
    expiry: '03-Dec-2024',
    sumInsured: 0,
    premium: 1000,
    status: 'Pending',
    vehicleRegistration: 'AUO 98B',
  },
];
