import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import "./styles.css";
import { cn } from "@app/lib/utils";
import "iconify-icon";
import Nprogressprovider from "@app/providers/Nprogress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("w-screen h-screen overflow-hidden", inter.className)}
      >
        <Nprogressprovider>{children}</Nprogressprovider>
      </body>
    </html>
  );
}
