import { Users } from './columns';

export const data: Users[] = [
  {
    id: 1,
    first_name: 'Alicea',
    last_name: 'Greves',
    email: 'agreves0@mapy.cz',
    gender: 'Female',
  },
  {
    id: 2,
    first_name: 'Thorny',
    last_name: 'Davidoff',
    email: 'tdavidoff1@discovery.com',
    gender: 'Male',
  },
  {
    id: 3,
    first_name: 'Evangelin',
    last_name: 'Cullinan',
    email: 'ecullinan2@t-online.de',
    gender: 'Female',
  },
  {
    id: 4,
    first_name: 'Brodie',
    last_name: 'Obal',
    email: 'bobal3@scribd.com',
    gender: 'Male',
  },
  {
    id: 5,
    first_name: 'Corry',
    last_name: 'Gaughan',
    email: 'cgaughan4@csmonitor.com',
    gender: 'Female',
  },
  {
    id: 6,
    first_name: 'Mora',
    last_name: 'Lipsett',
    email: 'mlipsett5@posterous.com',
    gender: 'Female',
  },
  {
    id: 7,
    first_name: 'Ashlie',
    last_name: 'Woollard',
    email: 'awoollard6@chicagotribune.com',
    gender: 'Female',
  },
  {
    id: 8,
    first_name: 'Tressa',
    last_name: 'Alten',
    email: 'talten7@pcworld.com',
    gender: 'Female',
  },
  {
    id: 9,
    first_name: 'Blondie',
    last_name: 'Dodwell',
    email: 'bdodwell8@census.gov',
    gender: 'Female',
  },
  {
    id: 10,
    first_name: 'Jessee',
    last_name: 'Woolaghan',
    email: 'jwoolaghan9@omniture.com',
    gender: 'Male',
  },
  {
    id: 11,
    first_name: 'Sukey',
    last_name: 'Antonat',
    email: 'santonata@blogs.com',
    gender: 'Female',
  },
  {
    id: 12,
    first_name: 'Hayward',
    last_name: 'Perelli',
    email: 'hperellib@unicef.org',
    gender: 'Male',
  },
  {
    id: 13,
    first_name: 'Doralin',
    last_name: 'Passe',
    email: 'dpassec@goo.ne.jp',
    gender: 'Female',
  },
  {
    id: 14,
    first_name: 'Abrahan',
    last_name: 'Clohissy',
    email: 'aclohissyd@si.edu',
    gender: 'Genderqueer',
  },
  {
    id: 15,
    first_name: 'Devondra',
    last_name: 'Gagen',
    email: 'dgagene@arizona.edu',
    gender: 'Female',
  },
  {
    id: 16,
    first_name: 'Elwira',
    last_name: 'Bloxland',
    email: 'ebloxlandf@archive.org',
    gender: 'Female',
  },
  {
    id: 17,
    first_name: 'Welch',
    last_name: 'Ragbourne',
    email: 'wragbourneg@uol.com.br',
    gender: 'Male',
  },
  {
    id: 18,
    first_name: 'Eduardo',
    last_name: 'Barltrop',
    email: 'ebarltroph@reference.com',
    gender: 'Male',
  },
  {
    id: 19,
    first_name: 'Orlan',
    last_name: 'Durrand',
    email: 'odurrandi@tumblr.com',
    gender: 'Male',
  },
  {
    id: 20,
    first_name: 'Bernarr',
    last_name: 'Palke',
    email: 'bpalkej@plala.or.jp',
    gender: 'Male',
  },
  {
    id: 21,
    first_name: 'Yorgo',
    last_name: 'Feldon',
    email: 'yfeldonk@reddit.com',
    gender: 'Male',
  },
  {
    id: 22,
    first_name: 'Worthy',
    last_name: 'Ferreo',
    email: 'wferreol@ft.com',
    gender: 'Male',
  },
  {
    id: 23,
    first_name: 'Trudey',
    last_name: 'Chaplyn',
    email: 'tchaplynm@wufoo.com',
    gender: 'Female',
  },
  {
    id: 24,
    first_name: 'Ronalda',
    last_name: 'Sheerman',
    email: 'rsheermann@amazon.de',
    gender: 'Female',
  },
  {
    id: 25,
    first_name: 'Glyn',
    last_name: 'Oakton',
    email: 'goaktono@theatlantic.com',
    gender: 'Male',
  },
  {
    id: 26,
    first_name: 'Fabio',
    last_name: 'Garber',
    email: 'fgarberp@networksolutions.com',
    gender: 'Male',
  },
  {
    id: 27,
    first_name: 'Ulla',
    last_name: 'Wildsmith',
    email: 'uwildsmithq@printfriendly.com',
    gender: 'Female',
  },
  {
    id: 28,
    first_name: 'Maggee',
    last_name: 'Whall',
    email: 'mwhallr@mail.ru',
    gender: 'Female',
  },
  {
    id: 29,
    first_name: 'Stace',
    last_name: 'Berresford',
    email: 'sberresfords@hubpages.com',
    gender: 'Female',
  },
  {
    id: 30,
    first_name: 'Alonzo',
    last_name: 'Attiwill',
    email: 'aattiwillt@nsw.gov.au',
    gender: 'Male',
  },
  {
    id: 31,
    first_name: 'Mikkel',
    last_name: 'Stuttman',
    email: 'mstuttmanu@jimdo.com',
    gender: 'Male',
  },
  {
    id: 32,
    first_name: 'Domingo',
    last_name: 'Cressy',
    email: 'dcressyv@multiply.com',
    gender: 'Male',
  },
  {
    id: 33,
    first_name: 'Cassie',
    last_name: 'Bonnell',
    email: 'cbonnellw@ustream.tv',
    gender: 'Male',
  },
  {
    id: 34,
    first_name: 'Abe',
    last_name: 'Brandoni',
    email: 'abrandonix@house.gov',
    gender: 'Male',
  },
  {
    id: 35,
    first_name: 'Donni',
    last_name: 'Latey',
    email: 'dlateyy@prnewswire.com',
    gender: 'Female',
  },
  {
    id: 36,
    first_name: 'Cosimo',
    last_name: 'Patman',
    email: 'cpatmanz@boston.com',
    gender: 'Male',
  },
  {
    id: 37,
    first_name: 'Iris',
    last_name: 'Walisiak',
    email: 'iwalisiak10@ning.com',
    gender: 'Bigender',
  },
  {
    id: 38,
    first_name: 'Claudia',
    last_name: 'Rozec',
    email: 'crozec11@ed.gov',
    gender: 'Female',
  },
  {
    id: 39,
    first_name: 'Doyle',
    last_name: 'Merrell',
    email: 'dmerrell12@cnbc.com',
    gender: 'Non-binary',
  },
  {
    id: 40,
    first_name: 'Nil',
    last_name: 'Aleksandrov',
    email: 'naleksandrov13@vinaora.com',
    gender: 'Male',
  },
  {
    id: 41,
    first_name: 'Erie',
    last_name: 'Tarbatt',
    email: 'etarbatt14@shinystat.com',
    gender: 'Male',
  },
  {
    id: 42,
    first_name: 'Hugibert',
    last_name: 'Evason',
    email: 'hevason15@ovh.net',
    gender: 'Male',
  },
  {
    id: 43,
    first_name: 'Sidnee',
    last_name: 'Sholem',
    email: 'ssholem16@dell.com',
    gender: 'Male',
  },
  {
    id: 44,
    first_name: 'Carlen',
    last_name: 'Haighton',
    email: 'chaighton17@exblog.jp',
    gender: 'Female',
  },
  {
    id: 45,
    first_name: 'Davidde',
    last_name: 'Grimsditch',
    email: 'dgrimsditch18@technorati.com',
    gender: 'Male',
  },
  {
    id: 46,
    first_name: 'Waiter',
    last_name: 'Schaffler',
    email: 'wschaffler19@deliciousdays.com',
    gender: 'Male',
  },
  {
    id: 47,
    first_name: 'Priscilla',
    last_name: 'Tawn',
    email: 'ptawn1a@economist.com',
    gender: 'Female',
  },
  {
    id: 48,
    first_name: 'Devy',
    last_name: 'Stickland',
    email: 'dstickland1b@ehow.com',
    gender: 'Male',
  },
  {
    id: 49,
    first_name: 'Rogers',
    last_name: 'McCluskey',
    email: 'rmccluskey1c@acquirethisname.com',
    gender: 'Male',
  },
  {
    id: 50,
    first_name: 'Winna',
    last_name: 'Hairs',
    email: 'whairs1d@craigslist.org',
    gender: 'Female',
  },
];
